packages:
  - 'packages/*'
  - 'demo'

overrides:
  '@angular-devkit/architect': 0.2201.8
  '@angular-devkit/core': 22.1.8
  '@angular-devkit/schematics': 22.1.8
  '@angular/cli': 22.1.8
  '@schematics/angular': 22.1.8
  glob: ^13.0.6
  immutable: ^5.1.9
  less: 4.9.1
  listr2: 11.1.0
  sass: ^1.104.1
  sharp: ^0.35.4

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
